name: Composite Action Secrets Test

inputs:
  formatted_secret:
    description: The formatted secret

runs:
  using: "composite"
  steps:
    - name: Test step
      shell: bash
      env:
        FORMATTED_SECRET: ${{ inputs.formatted_secret }}
      run: |
        printf 'The formatted secret is "%s"\n' "$FORMATTED_SECRET"
        printf 'The formatted secret is %s characters long\n' "${#FORMATTED_SECRET}"
        if [ "$FORMATTED_SECRET" = "/secret/" ]; then
          printf 'The formatted secret is correct\n'
        else
          printf 'The formatted secret is not correct\n'
        fi

