name: Workflow Secrets Test

on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-slim
    steps:
      - name: Formatted secret test
        env:
          FORMATTED_SECRET: ${{ format('/{0}/', secrets.SECRET) }}
        run: |
          printf 'The formatted secret is "%s"\n' "$FORMATTED_SECRET"
          printf 'The formatted secret is %s characters long\n' "${#FORMATTED_SECRET}"
          if [ "$FORMATTED_SECRET" = "/secret/" ]; then
            printf 'The formatted secret is correct\n'
          else
            printf 'The formatted secret is not correct\n'
          fi

      - name: Composite action test
        uses: $/.github/actions/composite
        with:
          formatted_secret: ${{ format('/{0}/', secrets.SECRET) }}

      - name: JavaScript action test
        uses: $/.github/actions/javascript
        with:
          formatted_secret: ${{ format('/{0}/', secrets.SECRET) }}

