name: Workflow Secrets Test

on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Test step
        env:
          SECRET: ${{ secrets.SECRET }}
        run: |
          printf 'The secret is "%s"\n' "$SECRET"
          printf 'The secret is %s characters long\n' "${#SECRET}"
